### PR TITLE
Fixed squashfs character device issue

### PR DESCRIPTION
**Pull request by ramsaut**
When extracting character devices from squashfs images the application hangs forever. This pull requests fixes this behavior and limits extraction to regular files, directories and links.

When extracting e.g. the [openwrt image](https://downloads.openwrt.org/releases/21.02.1/targets/x86/generic/openwrt-21.02.1-x86-generic-generic-squashfs-combined-efi.img.gz) it hangs forever without logging a reason.

It could be determined that the file `dev/console` inside `unpacked.gpt-partition1.part` could not be extracted.

The application attempts to copy the file using the following code from bangfilesystems.py

```
def local_copy2(src, dest):
    '''Wrapper around shutil.copy2 for squashfs unpacking'''
    return shutil.copy2(src, dest, follow_symlinks=False)
```

However, the file is a character device and the call therefore hangs forever.

I extended `unpack_squashfs` with a check to only copy directories, regular files or links.

### CODE REVIEW

**Comment by armijnhemel** [comment]
I actually cannot reproduce this and here it unpacks just fine. Can you tell a little bit more about your setup? For example, are you running the program as `root` or as a regular user?

**Comment by ramsaut** [comment]
Sure I try to gather all relevant information. Feel free to come back to me if anything is missing.

The following platform information is gathered by bang:
```
'platform': {'machine': 'x86_64', 'architecture': '64bit', 'processor': 'x86_64', 'node': '9451c56493a1', 'system': 'Linux', 'release': '5.15.7-arch1-1', 'libc': 'glibc', 'libcversion': '2.32'}, 'python': {'version': '3.9.9', 'implementation': 'CPython'}}
```
The program is executed in a Docker container.

I followed the following steps:

1. Generate base images by running `sudo make all` in the `util` folder
2. Build the bang container by running `sudo make ctrbuild` in `src`.
3. I run bang using podman

```bash
sudo podman container run -it --rm -v "${OUTPUT}":/unpack -v "${INPUTDIR}":/input -v "${SRC}":/src:z -v /tmp:/tmp:z -w /src bang python3 /src/bang-scanner -c bang.config -f /input/${INPUTFILE}
```

The `bang.config` was altered to match the mounted volumes in the command above.

**Comment by ramsaut** [comment]
I tried to gather additional logs. However, I can't reproduce the issue myself. I will therefore close.

**Comment by ramsaut** [comment]
I was able to narrow the problem down. It only occurs when bang is executed as root.

When I execute without root (`-u 1000`):
```
sudo docker run -it --rm -v "${OUTPUT}":/unpack -v "${INPUTDIR}":/input -v "${SRC}":/src:z -v /tmp:/tmp:z -u 1000 -w /src bang python3 /src/bang-scanner -c bang.config -f /input/${INPUTFILE}
```
unsquashfs returns with 
```
create_inode: could not create character device squashfs-root/dev/console, because you're not superuser!
```

Because dev console is already not created in this step the issue is prevented.

However, when the script is executed as root (`-u 0`):
```
sudo docker run -it --rm -v "${OUTPUT}":/unpack -v "${INPUTDIR}":/input -v "${SRC}":/src:z -v /tmp:/tmp:z -u 0 -w /src bang python3 /src/bang-scanner -c bang.config -f /input/${INPUTFILE}
```
The file is created and the above issue occurs, when `dev/console` is copied using `shutil.copy2`.

**Comment by armijnhemel** [comment]
Thanks. This is what I thought was happening. As I am refactoring anyway I will take this particular situation into account.

**Comment by armijnhemel** [comment]
I fixed the bug in a different way, see https://github.com/armijnhemel/binaryanalysis-ng/pull/284

It seems that you added some different unrelated things to this PR. You might want to rework that (no guarantees that I will merge it, everything is currently in flux).

**Comment by ramsaut** [comment]
Thank you.
Sorry for the unrelated things.

**Pull request closed without merging**
